# Generated by Django 4.2.30 on 2026-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Nightlife', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='slots_left',
            field=models.PositiveIntegerField(default=0, help_text='Remaining tickets available'),
        ),
    ]
