# Generated by Django 4.2.30 on 2026-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_remove_ticket_user_ticket_attendee_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Turn Up Kenya', max_length=120)),
                ('tagline', models.TextField(default='Book tickets to concerts, nightlife and culture events across Kenya.')),
                ('support_email', models.EmailField(default='hello@turnupkenya.com', max_length=254)),
                ('support_phone', models.CharField(default='+254 700 000 000', max_length=30)),
                ('paybill', models.CharField(default='123456', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, default='Turn Up Kenya. Book event tickets online with M-Pesa. Instant QR passes for parties, concerts and festivals.')),
                ('meta_keywords', models.CharField(blank=True, default='Turn Up Kenya, event tickets, M-Pesa tickets, Nairobi events, concerts, nightlife', max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
