# Generated by Django 4.2.30 on 2026-05-27 22:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Site favicon (PNG, JPG, or SVG).', null=True, upload_to='site/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='events/banners/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='events/posters/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/', validators=[core.validators.validate_image_file]),
        ),
    ]
