"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _csv_hosts(value):
    if not value:
        return []
    hosts = []
    for item in value.split(","):
        item = item.strip()
        if not item:
            continue
        if "://" in item:
            item = urlparse(item).hostname or item
        item = item.strip("/")
        if item and item not in hosts:
            hosts.append(item)
    return hosts


def _csv_origins(value):
    if not value:
        return []
    origins = []
    for item in value.split(","):
        item = item.strip().rstrip("/")
        if not item:
            continue
        if "://" not in item:
            item = f"https://{item}"
        if item not in origins:
            origins.append(item)
    return origins


def _origin_from_url(url):
    parsed = urlparse((url or "").strip())
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

RAILWAY_PUBLIC_DOMAIN = config("RAILWAY_PUBLIC_DOMAIN", default="")
SITE_URL = config("SITE_URL", default="").rstrip("/")
if not SITE_URL and RAILWAY_PUBLIC_DOMAIN:
    SITE_URL = f"https://{RAILWAY_PUBLIC_DOMAIN.strip()}"
elif SITE_URL.startswith("http://") and (RAILWAY_PUBLIC_DOMAIN or not DEBUG):
    SITE_URL = "https://" + SITE_URL[len("http://") :]
elif SITE_URL and not SITE_URL.startswith("http"):
    SITE_URL = f"https://{SITE_URL.lstrip('/')}"

ALLOWED_HOSTS = _csv_hosts(config("ALLOWED_HOSTS", default="127.0.0.1,localhost"))
if "*" in ALLOWED_HOSTS:
    ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h != "*"]
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN.strip())

for _url in (SITE_URL, config("SPARKPESA_CALLBACK_URL", default="")):
    _host = urlparse(_url.strip()).hostname if _url else None
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

CSRF_TRUSTED_ORIGINS = _csv_origins(config("CSRF_TRUSTED_ORIGINS", default=""))
if SITE_URL:
    _site_origin = _origin_from_url(SITE_URL)
    if _site_origin and _site_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_site_origin)
if RAILWAY_PUBLIC_DOMAIN:
    _railway_origin = f"https://{RAILWAY_PUBLIC_DOMAIN.strip()}"
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)
for _url in (config("SPARKPESA_CALLBACK_URL", default=""),):
    _origin = _origin_from_url(_url)
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_database_url = config("DATABASE_URL", default=os.environ.get("DATABASE_URL", ""))
if _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif config("DB_ENGINE", default="sqlite") == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="ticketing"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="postgres"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {"timeout": 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
_volume_mount = os.environ.get("RAILWAY_VOLUME_MOUNT_PATH", "").strip()
if _volume_mount:
    MEDIA_ROOT = Path(_volume_mount)
else:
    MEDIA_ROOT = Path(config("MEDIA_ROOT", default=str(BASE_DIR / "media")))

LOGIN_URL = "portal_login"
LOGIN_REDIRECT_URL = "portal_dashboard"
LOGOUT_REDIRECT_URL = "home"

def _env_str(key, default=""):
    return str(config(key, default=default) or "").strip().strip('"').strip("'")


EMAIL_BACKEND = _env_str(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = _env_str("EMAIL_HOST", "das126.truehost.cloud")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = _env_str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = _env_str("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = _env_str("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER or "info@turnupkenya.top"
ADMIN_EMAIL = _env_str("ADMIN_EMAIL") or DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

# Resend (recommended on Railway — SMTP ports are often blocked)
RESEND_API_KEY = _env_str("RESEND_API_KEY")
RESEND_FROM_EMAIL = _env_str("RESEND_FROM_EMAIL") or DEFAULT_FROM_EMAIL

SPARKPESA_API_KEY = config("SPARKPESA_API_KEY", default="")
SPARKPESA_API_SECRET = config("SPARKPESA_API_SECRET", default="")
SPARKPESA_WALLET_CODE = config("SPARKPESA_WALLET_CODE", default="")
SPARKPESA_WALLET_ID = config("SPARKPESA_WALLET_ID", default="")
SPARKPESA_BASE_URL = config("SPARKPESA_BASE_URL", default="https://www.sparkpesa.io/api/v1")
SPARKPESA_WEBHOOK_URL = config("SPARKPESA_WEBHOOK_URL", default="")
SPARKPESA_CALLBACK_URL = config("SPARKPESA_CALLBACK_URL", default="")
if not SPARKPESA_CALLBACK_URL and SITE_URL:
    SPARKPESA_CALLBACK_URL = f"{SITE_URL}/webhooks/sparkpesa/"
if not SPARKPESA_WEBHOOK_URL and SPARKPESA_CALLBACK_URL:
    SPARKPESA_WEBHOOK_URL = SPARKPESA_CALLBACK_URL

# Production / Railway
if RAILWAY_PUBLIC_DOMAIN or not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
